title: Matteo Luceri # your name (or website title) here
logo: "/images/new.png?raw=true"  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Creative and people-oriented Computer Scientist eager to contribute to team success through hard work, attention to detail and excellent organizational skills.
  Motivated to learn, grow and excel.
  <br><br>
  Main focus on OOP, UX and Calculus
  <br><br>
  <a href="www.linkedin.com/in/matteoluceri/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
